// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/config.dart';
import 'api/models.dart';
import 'api/storage.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 170532783;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'UNKNOWN',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<WaffleStorage> crateApiStorageWaffleStorageInit({
    required WaffleConfig config,
  });

  Future<Uint8List?> crateApiStorageWaffleStorageReadMetadata({
    required WaffleStorage that,
    required String id,
  });

  Future<bool> crateApiStorageWaffleStorageWriteMetadata({
    required WaffleStorage that,
    required String id,
    required List<double> vector,
    required VectorMetadata metadata,
  });

  Future<void> crateApiStorageWaffleStorageWriteRecord({
    required WaffleStorage that,
    required String id,
    required List<double> vector,
    required List<int> metadata,
  });

  Future<WaffleConfig> crateApiConfigWaffleConfigDefault();

  Future<WaffleConfig> crateApiConfigWaffleConfigMobileProfile({
    required String path,
    required int dimension,
  });

  Future<WaffleConfig> crateApiConfigWaffleConfigReadHeavyProfile({
    required String path,
    required int dimension,
  });

  Future<WaffleConfig> crateApiConfigWaffleConfigServerProfile({
    required String path,
    required int dimension,
  });

  Future<WaffleConfig> crateApiConfigWaffleConfigWriteHeavyProfile({
    required String path,
    required int dimension,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WaffleStorage;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WaffleStorage;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_WaffleStoragePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<WaffleStorage> crateApiStorageWaffleStorageInit({
    required WaffleConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_waffle_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaffleStorage,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageWaffleStorageInitConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageWaffleStorageInitConstMeta =>
      const TaskConstMeta(
        debugName: "WaffleStorage_init",
        argNames: ["config"],
      );

  @override
  Future<Uint8List?> crateApiStorageWaffleStorageReadMetadata({
    required WaffleStorage that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaffleStorage(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageWaffleStorageReadMetadataConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageWaffleStorageReadMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "WaffleStorage_read_metadata",
        argNames: ["that", "id"],
      );

  @override
  Future<bool> crateApiStorageWaffleStorageWriteMetadata({
    required WaffleStorage that,
    required String id,
    required List<double> vector,
    required VectorMetadata metadata,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaffleStorage(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          sse_encode_list_prim_f_32_loose(vector, serializer);
          sse_encode_box_autoadd_vector_metadata(metadata, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageWaffleStorageWriteMetadataConstMeta,
        argValues: [that, id, vector, metadata],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageWaffleStorageWriteMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "WaffleStorage_write_metadata",
        argNames: ["that", "id", "vector", "metadata"],
      );

  @override
  Future<void> crateApiStorageWaffleStorageWriteRecord({
    required WaffleStorage that,
    required String id,
    required List<double> vector,
    required List<int> metadata,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaffleStorage(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          sse_encode_list_prim_f_32_loose(vector, serializer);
          sse_encode_list_prim_u_8_loose(metadata, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageWaffleStorageWriteRecordConstMeta,
        argValues: [that, id, vector, metadata],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageWaffleStorageWriteRecordConstMeta =>
      const TaskConstMeta(
        debugName: "WaffleStorage_write_record",
        argNames: ["that", "id", "vector", "metadata"],
      );

  @override
  Future<WaffleConfig> crateApiConfigWaffleConfigDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_waffle_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigWaffleConfigDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigWaffleConfigDefaultConstMeta =>
      const TaskConstMeta(debugName: "waffle_config_default", argNames: []);

  @override
  Future<WaffleConfig> crateApiConfigWaffleConfigMobileProfile({
    required String path,
    required int dimension,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_u_32(dimension, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_waffle_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigWaffleConfigMobileProfileConstMeta,
        argValues: [path, dimension],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigWaffleConfigMobileProfileConstMeta =>
      const TaskConstMeta(
        debugName: "waffle_config_mobile_profile",
        argNames: ["path", "dimension"],
      );

  @override
  Future<WaffleConfig> crateApiConfigWaffleConfigReadHeavyProfile({
    required String path,
    required int dimension,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_u_32(dimension, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_waffle_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigWaffleConfigReadHeavyProfileConstMeta,
        argValues: [path, dimension],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigWaffleConfigReadHeavyProfileConstMeta =>
      const TaskConstMeta(
        debugName: "waffle_config_read_heavy_profile",
        argNames: ["path", "dimension"],
      );

  @override
  Future<WaffleConfig> crateApiConfigWaffleConfigServerProfile({
    required String path,
    required int dimension,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_u_32(dimension, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_waffle_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigWaffleConfigServerProfileConstMeta,
        argValues: [path, dimension],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigWaffleConfigServerProfileConstMeta =>
      const TaskConstMeta(
        debugName: "waffle_config_server_profile",
        argNames: ["path", "dimension"],
      );

  @override
  Future<WaffleConfig> crateApiConfigWaffleConfigWriteHeavyProfile({
    required String path,
    required int dimension,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_u_32(dimension, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_waffle_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigWaffleConfigWriteHeavyProfileConstMeta,
        argValues: [path, dimension],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigWaffleConfigWriteHeavyProfileConstMeta =>
      const TaskConstMeta(
        debugName: "waffle_config_write_heavy_profile",
        argNames: ["path", "dimension"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WaffleStorage => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaffleStorage;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WaffleStorage => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaffleStorage;

  @protected
  WaffleStorage
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaffleStorage(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WaffleStorageImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WaffleStorage
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaffleStorage(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WaffleStorageImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WaffleStorage
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaffleStorage(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WaffleStorageImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  VectorMetadata dco_decode_box_autoadd_vector_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_vector_metadata(raw);
  }

  @protected
  WaffleConfig dco_decode_box_autoadd_waffle_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_waffle_config(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VectorMetadata dco_decode_vector_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VectorMetadata(
      title: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
      category: dco_decode_String(arr[2]),
      payload: dco_decode_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  WaffleConfig dco_decode_waffle_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return WaffleConfig(
      dimension: dco_decode_u_32(arr[0]),
      path: dco_decode_String(arr[1]),
      graphConfig: dco_decode_waffle_graph_config(arr[2]),
      maxElements: dco_decode_u_32(arr[3]),
      useQuantization: dco_decode_bool(arr[4]),
      cacheSizeBytes: dco_decode_u_64(arr[5]),
      workerThreads: dco_decode_u_32(arr[6]),
    );
  }

  @protected
  WaffleGraphConfig dco_decode_waffle_graph_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return WaffleGraphConfig(
      m: dco_decode_u_32(arr[0]),
      metric: dco_decode_waffle_metric(arr[1]),
      efConstruction: dco_decode_u_32(arr[2]),
      efSearch: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  WaffleMetric dco_decode_waffle_metric(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WaffleMetric.values[raw as int];
  }

  @protected
  WaffleStorage
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaffleStorage(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WaffleStorageImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WaffleStorage
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaffleStorage(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WaffleStorageImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WaffleStorage
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaffleStorage(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WaffleStorageImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  VectorMetadata sse_decode_box_autoadd_vector_metadata(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_vector_metadata(deserializer));
  }

  @protected
  WaffleConfig sse_decode_box_autoadd_waffle_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_waffle_config(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VectorMetadata sse_decode_vector_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_payload = sse_decode_list_prim_u_8_strict(deserializer);
    return VectorMetadata(
      title: var_title,
      description: var_description,
      category: var_category,
      payload: var_payload,
    );
  }

  @protected
  WaffleConfig sse_decode_waffle_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dimension = sse_decode_u_32(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_graphConfig = sse_decode_waffle_graph_config(deserializer);
    var var_maxElements = sse_decode_u_32(deserializer);
    var var_useQuantization = sse_decode_bool(deserializer);
    var var_cacheSizeBytes = sse_decode_u_64(deserializer);
    var var_workerThreads = sse_decode_u_32(deserializer);
    return WaffleConfig(
      dimension: var_dimension,
      path: var_path,
      graphConfig: var_graphConfig,
      maxElements: var_maxElements,
      useQuantization: var_useQuantization,
      cacheSizeBytes: var_cacheSizeBytes,
      workerThreads: var_workerThreads,
    );
  }

  @protected
  WaffleGraphConfig sse_decode_waffle_graph_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_m = sse_decode_u_32(deserializer);
    var var_metric = sse_decode_waffle_metric(deserializer);
    var var_efConstruction = sse_decode_u_32(deserializer);
    var var_efSearch = sse_decode_u_32(deserializer);
    return WaffleGraphConfig(
      m: var_m,
      metric: var_metric,
      efConstruction: var_efConstruction,
      efSearch: var_efSearch,
    );
  }

  @protected
  WaffleMetric sse_decode_waffle_metric(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return WaffleMetric.values[inner];
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaffleStorage(
    WaffleStorage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WaffleStorageImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaffleStorage(
    WaffleStorage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WaffleStorageImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaffleStorage(
    WaffleStorage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WaffleStorageImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_vector_metadata(
    VectorMetadata self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vector_metadata(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_waffle_config(
    WaffleConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_waffle_config(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_vector_metadata(
    VectorMetadata self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_list_prim_u_8_strict(self.payload, serializer);
  }

  @protected
  void sse_encode_waffle_config(WaffleConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.dimension, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_waffle_graph_config(self.graphConfig, serializer);
    sse_encode_u_32(self.maxElements, serializer);
    sse_encode_bool(self.useQuantization, serializer);
    sse_encode_u_64(self.cacheSizeBytes, serializer);
    sse_encode_u_32(self.workerThreads, serializer);
  }

  @protected
  void sse_encode_waffle_graph_config(
    WaffleGraphConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.m, serializer);
    sse_encode_waffle_metric(self.metric, serializer);
    sse_encode_u_32(self.efConstruction, serializer);
    sse_encode_u_32(self.efSearch, serializer);
  }

  @protected
  void sse_encode_waffle_metric(WaffleMetric self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}

@sealed
class WaffleStorageImpl extends RustOpaque implements WaffleStorage {
  // Not to be used by end users
  WaffleStorageImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  WaffleStorageImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_WaffleStorage,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_WaffleStorage,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_WaffleStoragePtr,
  );

  Future<Uint8List?> readMetadata({required String id}) => RustLib.instance.api
      .crateApiStorageWaffleStorageReadMetadata(that: this, id: id);

  Future<bool> writeMetadata({
    required String id,
    required List<double> vector,
    required VectorMetadata metadata,
  }) => RustLib.instance.api.crateApiStorageWaffleStorageWriteMetadata(
    that: this,
    id: id,
    vector: vector,
    metadata: metadata,
  );

  Future<void> writeRecord({
    required String id,
    required List<double> vector,
    required List<int> metadata,
  }) => RustLib.instance.api.crateApiStorageWaffleStorageWriteRecord(
    that: this,
    id: id,
    vector: vector,
    metadata: metadata,
  );
}
