// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

class WaffleConfig {
  final int dimension;
  final String path;
  final WaffleGraphConfig graphConfig;
  final int maxElements;
  final bool useQuantization;
  final BigInt cacheSizeBytes;
  final int workerThreads;

  const WaffleConfig({
    required this.dimension,
    required this.path,
    required this.graphConfig,
    required this.maxElements,
    required this.useQuantization,
    required this.cacheSizeBytes,
    required this.workerThreads,
  });

  static Future<WaffleConfig> default_() =>
      RustLib.instance.api.crateApiConfigWaffleConfigDefault();

  static Future<WaffleConfig> mobileProfile({
    required String path,
    required int dimension,
  }) => RustLib.instance.api.crateApiConfigWaffleConfigMobileProfile(
    path: path,
    dimension: dimension,
  );

  static Future<WaffleConfig> readHeavyProfile({
    required String path,
    required int dimension,
  }) => RustLib.instance.api.crateApiConfigWaffleConfigReadHeavyProfile(
    path: path,
    dimension: dimension,
  );

  static Future<WaffleConfig> serverProfile({
    required String path,
    required int dimension,
  }) => RustLib.instance.api.crateApiConfigWaffleConfigServerProfile(
    path: path,
    dimension: dimension,
  );

  static Future<WaffleConfig> writeHeavyProfile({
    required String path,
    required int dimension,
  }) => RustLib.instance.api.crateApiConfigWaffleConfigWriteHeavyProfile(
    path: path,
    dimension: dimension,
  );

  @override
  int get hashCode =>
      dimension.hashCode ^
      path.hashCode ^
      graphConfig.hashCode ^
      maxElements.hashCode ^
      useQuantization.hashCode ^
      cacheSizeBytes.hashCode ^
      workerThreads.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WaffleConfig &&
          runtimeType == other.runtimeType &&
          dimension == other.dimension &&
          path == other.path &&
          graphConfig == other.graphConfig &&
          maxElements == other.maxElements &&
          useQuantization == other.useQuantization &&
          cacheSizeBytes == other.cacheSizeBytes &&
          workerThreads == other.workerThreads;
}

class WaffleGraphConfig {
  final int m;
  final WaffleMetric metric;
  final int efConstruction;
  final int efSearch;

  const WaffleGraphConfig({
    required this.m,
    required this.metric,
    required this.efConstruction,
    required this.efSearch,
  });

  @override
  int get hashCode =>
      m.hashCode ^
      metric.hashCode ^
      efConstruction.hashCode ^
      efSearch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WaffleGraphConfig &&
          runtimeType == other.runtimeType &&
          m == other.m &&
          metric == other.metric &&
          efConstruction == other.efConstruction &&
          efSearch == other.efSearch;
}

enum WaffleMetric { cosine, euclidean, dotProduct }
