// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HnswIndex`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `get_nb_point`, `insert_slice`, `insert`, `new`, `search`

/// Standalone cosine similarity for Dart FFI use.
Future<double> cosineSimilarity({
  required List<double> a,
  required List<double> b,
}) => RustLib.instance.api.crateApiMathCosineSimilarity(a: a, b: b);
