// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HnswIndex`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `get_nb_point`, `insert_slice`, `insert`, `load`, `new`, `save`, `search`

/// Standalone cosine similarity for Dart FFI use.
///
/// Calculates the cosine similarity between two vectors.
/// Returns a value between -1.0 and 1.0 (1.0 means identical direction).
///
/// Example:
/// ```dart
/// final similarity = await cosineSimilarity(a: [1.0, 0.0], b: [1.0, 0.0]);
/// print(similarity); // 1.0
/// ```
Future<double> cosineSimilarity({
  required List<double> a,
  required List<double> b,
}) => RustLib.instance.api.crateApiMathCosineSimilarity(a: a, b: b);
