// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ArchivedVectorMetadata`, `VectorMetadataResolver`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `check_bytes`, `deserialize`, `fmt`, `resolve`, `serialize`

class VectorMetadata {
  final String title;
  final String description;
  final String category;
  final Uint8List payload;

  const VectorMetadata({
    required this.title,
    required this.description,
    required this.category,
    required this.payload,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      description.hashCode ^
      category.hashCode ^
      payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VectorMetadata &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          description == other.description &&
          category == other.category &&
          payload == other.payload;
}

/// Result returned from a KNN query, bridgeable by FRB.
class WaffleQueryResult {
  final String id;
  final double distance;
  final Uint8List? metadata;

  const WaffleQueryResult({
    required this.id,
    required this.distance,
    this.metadata,
  });

  @override
  int get hashCode => id.hashCode ^ distance.hashCode ^ metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WaffleQueryResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          distance == other.distance &&
          metadata == other.metadata;
}
