// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'config.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WaffleStorage>>
abstract class WaffleStorage implements RustOpaqueInterface {
  Future<BigInt> count();

  Future<bool> deleteRecord({required String id});

  Future<void> flush();

  /// Returns all stored string IDs.
  Future<List<String>> getAllIds();

  /// Returns all stored (id, vector) pairs for rebuilding the HNSW index.
  Future<List<(String, Float32List)>> getAllVectors({required BigInt dim});

  static Future<WaffleStorage> init({required WaffleConfig config}) =>
      RustLib.instance.api.crateApiStorageWaffleStorageInit(config: config);

  Future<Uint8List?> readMetadata({required String id});

  Future<Float32List?> readVector({required String id, required BigInt dim});

  Future<bool> writeMetadata({
    required String id,
    required List<double> vector,
    required VectorMetadata metadata,
  });

  Future<void> writeRecord({
    required String id,
    required List<double> vector,
    required List<int> metadata,
  });
}
